-- MODELO FISICO

CREATE TABLE Shops (
	shop_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	address VARCHAR2(200),
	city VARCHAR2(70),
	opening_hours VARCHAR2(200)
);

CREATE TABLE Sales (
	sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	date1 DATE DEFAULT SYSDATE,
	total_amount NUMBER,
	email VARCHAR2(70),
	shop_id NUMBER CONSTRAINT fk_shop_id REFERENCES Shops(shop_id)
);

CREATE TABLE Products (
	product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR2(80),
	price NUMBER,
	stock NUMBER,
	image_url VARCHAR2(300)
);

CREATE TABLE SaleDetail (
	sale_id CONSTRAINT fk_sale_id REFERENCES Sales(sale_id),
	product_id CONSTRAINT fk_product_id REFERENCES Products(product_id),
	quantity NUMBER
);