-- Creación de usuario

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER admin IDENTIFIED BY password;


GRANT CREATE SESSION TO admin;
GRANT CREATE TABLE TO admin;
GRANT ALTER ANY TABLE TO admin;
GRANT CREATE VIEW TO admin;
GRANT DROP ANY TABLE TO admin;
GRANT SELECT ANY TABLE TO admin;
GRANT CREATE ANY INDEX TO admin;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO admin;

-- Creación de las tablas

CREATE TABLE Shops (
	shop_id NUMBER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	address VARCHAR2(200),
	city VARCHAR2(70),
	opening_hours VARCHAR2(200)
);

CREATE TABLE Sales (
	sale_id NUMBER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	date DATE DEFAULT SYSDATE,
	total_amount NUMBER,
	email VARCHAR2(70),
	shop_id NUMBER CONSTRAINT fk_shop_id REFERENCES Shops(shop_id)
);

CREATE TABLE Products (
	product_id NUMBER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR2(80),
	price NUMBER,
	stock NUMBER,
	image_url VARCHAR2(300),
);

CREATE TABLE SaleDetail (
	sale_id CONSTRAINT fk_sale_id REFERENCES Sales(sale_id),
	product_id CONSTRAINT fk_product_id REFERENCES Products(product_id),
	quantity NUMBER
);

-- Parametrización inicial de las tablas

CREATE OR REPLACE PROCEDURE SCRIPT_INICIALIZACION_TABLAS
	AS
	BEGIN
		INSERT INTO Shops(address, city, opening_hours)
		VALUES ('45 Alfonso St', 'Zaragoza', 'Monday to Friday 9h to 20h');
		INSERT INTO Shops(address, city, opening_hours)
		VALUES ('46 Mayor St', 'Madrid', 'Monday to Friday 9h to 20h');
        
		INSERT INTO Products(name, price, stock, image_url)
		VALUES ('Pencil', 0.5, 80, 'https://www.collinsdictionary.com/images/full/pencil_280523090.jpg');
		INSERT INTO Products(name, price, stock, image_url)
		VALUES ('Eraser', 1.5, 50, 'https://i.ebayimg.com/images/g/DX4AAOxyRNJScXF-/s-l1200.jpg');
		INSERT INTO Products(name, price, stock, image_url)
		VALUES ('Pencil Sharpener', 2, 15, 'https://i.ebayimg.com/images/g/j24AAOSwxuha~AV-/s-l1200.jpg');
		INSERT INTO Products(name, price, stock, image_url)
		VALUES ('Fountain Pen', 0.5, 80, 'https://www.penboutique.com/cdn/shop/files/Montblanc-Meisterstuck-Fountain-Pen-149-Black-Red-Gold-Trim-Montblanc-42473361.jpg?v=1708824108');
	
		COMMIT;
	EXCEPTION
		WHEN OTHERS THEN
			ROLLBACK;
	END SCRIPT_INICIALIZACION_TABLAS;
			
EXECUTE SCRIPT_INICIALIZACION_TABLAS;