ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER web_admin1 IDENTIFIED BY password11;

GRANT CREATE SESSION TO web_admin1;
GRANT CREATE TABLE TO web_admin1;
GRANT ALTER ANY TABLE TO web_admin1;
GRANT CREATE VIEW TO web_admin1;
GRANT DROP ANY TABLE TO web_admin1;
GRANT SELECT ANY TABLE TO web_admin1;
GRANT CREATE ANY INDEX TO web_admin1;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO web_admin1;
GRANT CREATE SEQUENCE TO web_admin1;
GRANT CREATE PROCEDURE TO web_admin1;
GRANT EXECUTE ANY PROCEDURE TO web_admin1;
GRANT UNLIMITED TABLESPACE TO web_admin1;